#pragma config(Sensor, S1,     bumper,              sensorTouch)
#pragma config(Sensor, S4,     sonar,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "move.c"
#define DESIRED_DISTANCE 30
#define SPEED_DIST_R 1

static bool LED_flashing = false;

task LED () {
  while(true) {
    if(SensorValue[bumper]) {
      motor[motorA] = 100;
    } else {
      motor[motorA] = 0;
    }
  }
}

task drive() {
  while(true) {
    if(SensorValue[bumper]) {
      motor[motorB] = 0;
      motor[motorC] = 0;
    }
  }
}

task sonar_distance() {
  while(true) {
    int speed = -SPEED_DIST_R * (DESIRED_DISTANCE - SensorValue[sonar]);
    motor[motorB] = speed;
    motor[motorC] = speed;
  }
}

task sonar_tone() {
  while(true) {
    PlayTone(10*SensorValue[sonar], 1);
  }
}

task main() {
  nMotorPIDSpeedCtrl[motorA] = mtrNoReg;
  StartTask(sonar_tone);
  StartTask(sonar_distance);
  StartTask(LED);
  StartTask(drive);
  while(true);
}

