#pragma config(Sensor, S2,     right_bump,          sensorTouch)
#pragma config(Sensor, S1,     right_light,         sensorLightInactive)
#pragma config(Sensor, S4,     left_light,          sensorLightInactive)
#pragma config(Sensor, S3,     left_bump,           sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "move.c"

static int bump_direction = 0;

// Reverses then turns away from bump direction
// Defaults right if head-on bump
task collision() {
  if (bump_direction == 0) bump_direction = -1;
  reverse(10);
  rotate(bump_direction * 30);
}

task idling() {
  motor[motorB] = 50;
  motor[motorC] = 50;
}

task main() {
  while(true) {
    if(SensorValue[right_bump] || SensorValue[left_bump]) {
      bump_direction = -1 * SensorValue[right_bump] + SensorValue[left_bump];
      StartTask(collision, 10);
    } else {
      StartTask(idling);
    }
  }
}
