#pragma config(Sensor, S1,     right_bump,          sensorTouch)
#pragma config(Sensor, S2,     right_light,         sensorLightInactive)
#pragma config(Sensor, S3,     left_light,          sensorLightInactive)
#pragma config(Sensor, S4,     left_bump,           sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "move.c"

// Swaps off currently active secondary task with given one
void swap_task(void *taskId) {
  static void *currentTaskId = 0;
  if(currentTaskId) {
    StopTask(currentTaskId);
  }
  currentTaskId = taskId;
  StartTask(taskId);
}

// Reverses then turns away from bump direction
// Defaults right if head-on bump
task collision() {
  int direction = SensorValue[left_bump] || -1;

  reverse(10);
  rotate(direction * 30);
}

task idling() {
  motor[motorB] = 50;
  motor[motorC] = 50;
}

task main() {
  while(true) {
    if(SensorValue[right_bump] || SensorValue[left_bump]) {
      swap_task(&collision);
    } else {
      swap_task(&idling);
    }
  }
}
