#pragma config(Sensor, S2,     right_bump,          sensorTouch)
#pragma config(Sensor, S1,     right_light,         sensorLightInactive)
#pragma config(Sensor, S4,     left_light,          sensorLightInactive)
#pragma config(Sensor, S3,     left_bump,           sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "move.c"

static int bump_direction = 0;

// Reverses then turns away from bump direction
// Defaults right if head-on bump
task collision() {
  if (bump_direction == 0) bump_direction = -1;
  reverse(100);
  rotate(bump_direction * 30);
  forward(100);
}

task follow_light() {
  motor[motorB] = SensorValue[left_light];
  motor[motorC] = SensorValue[right_light];
}

task idling() {
  motor[motorB] = 10;
  motor[motorC] = -10;
}

task main() {
  while(true) {
    if(SensorValue[right_light] > 70 || SensorValue[left_light] > 70) {
      PlaySound(soundDownwardTones);
      stop(1000);
      break;
    } else if(SensorValue[right_bump] || SensorValue[left_bump]) {
      bump_direction = -1 * SensorValue[right_bump] + SensorValue[left_bump];
      StartTask(collision, 10);
    } else if(SensorValue[right_light] > 30 || SensorValue[left_light] > 30) {
      StartTask(follow_light);
    } else {
      StartTask(idling);
    }
  }
}
